### ISSUE TITLE
Rename `*.oql` files to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [jimmyrocks/conflatify#1] opened 2022-09-24 16:17 UTC
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment] 2023-02-23 20:48
@jimmyrocks Would a pull request be accepted?

**Comment by jimmyrocks** [comment] 2023-02-23 20:54
I haven't touched this repo in years, and I probably should archive it, but it does still what was intended to do. If you have the time to update the file names, I'd accept a pull request. I can do it too, it's mostly a find/replace operation.

**Comment by FloEdelmann** [comment] 2023-02-23 20:57
@jimmyrocks Given that a rename still helps the wider community in making syntax highlighting support on GitHub more likely, it'd be great!

**Comment by jimmyrocks** [comment] 2023-02-23 21:00
@FloEdelmann excellent, I'll do the rename and close this issue tonight. Thanks for letting me know, and reminding me.

**Comment by jimmyrocks** [comment] 2023-02-24 02:37
Fixed with commits: d01ba42ff436b8041fb6ae6d5bcfdbd0f9c0065c, 3349b2f121861b8e8451186e57f1da852616fea4, and d7f574d0814b172c80be474b0e0e24301cb8242f

**Closed as completed by jimmyrocks** 2023-02-24 02:37 UTC

**Comment by FloEdelmann** [comment] 2023-02-24 08:17
Thanks for renaming!
